# Generated by Django 5.0.1 on 2024-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postview',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
