# Generated by Django 5.0.1 on 2024-02-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
