# Generated by Django 5.0.1 on 2024-02-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_alter_firm_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
