# Generated by Django 5.0.1 on 2024-02-06 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_alter_purchase_price_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
