# Generated by Django 5.0.1 on 2024-02-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_alter_firm_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
    ]
